import subprocess
import os
import sys

def call_sub_agent(prompt):
    """
    Dispatches a task to the sub-agent environment via run_sub_agent.sh.
    
    Args:
        prompt (str): The instruction for the sub-agent.
        
    Returns:
        str: The content generated by the sub-agent, or None on failure.
    """
    
    # Resolve paths
    script_dir = os.path.dirname(os.path.abspath(__file__))
    bash_script = os.path.join(script_dir, "run_sub_agent.sh")
    
    # Locate Bash executable (Git Bash usually)
    # This tries standard locations; might need adjustment based on system
    bash_exe = r"C:\Program Files\Git\bin\bash.exe"
    
    if not os.path.exists(bash_exe):
        # Fallback to just 'bash' if not found at specific path
        bash_exe = "bash"

    print(f"--- Dispatching Agent Task ---")
    print(f"Prompt: {prompt[:50]}..." if len(prompt) > 50 else f"Prompt: {prompt}")

    try:
        # Run the bash script
        # We capture stdout/stderr to extract the result cleanly if needed,
        # but the bash script already prints the output at the end.
        # Ideally, we want to read the actual output file for the return value.
        
        result = subprocess.run(
            [bash_exe, bash_script, prompt],
            capture_output=True,
            text=True,
            encoding='utf-8' # Force UTF-8 for Chinese support
        )
        
        if result.returncode != 0:
            print(f"Error executing agent script: {result.stderr}")
            return None

        # To get the PURE result programmatically, we should read the file directly
        # rather than parsing stdout.
        workspace_dir = os.path.join(os.path.dirname(script_dir), "Sub_Agent_Workspace")
        output_file = os.path.join(workspace_dir, "task_output.md")
        
        if os.path.exists(output_file):
            with open(output_file, 'r', encoding='utf-8') as f:
                content = f.read().strip()
                print(f"--- Agent Result ---\n{content}\n--------------------")
                return content
        else:
            print("Error: Output file not found.")
            return None

    except Exception as e:
        print(f"Exception during agent dispatch: {e}")
        return None

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python call_agent_task.py \"<Prompt Text or File Path>\"")
        sys.exit(1)
    
    input_val = sys.argv[1]
    
    # Check if input is a file path
    if os.path.isfile(input_val):
        print(f"Reading prompt from file: {input_val}")
        try:
            with open(input_val, 'r', encoding='utf-8') as f:
                user_prompt = f.read()
        except Exception as e:
            print(f"Error reading prompt file: {e}")
            sys.exit(1)
    else:
        # Join all arguments as the prompt
        user_prompt = " ".join(sys.argv[1:])
    
    call_sub_agent(user_prompt)
